export const ROUTES = {
  login: '/login',
  dashboard: '/',
  customers: '/customers',
  customerNew: '/customers/new',
  customerDetail: (id: string) => `/customers/${id}`,
  customerEdit: (id: string) => `/customers/${id}/edit`,
  pets: '/pets',
  petNew: '/pets/new',
  petDetail: (id: string) => `/pets/${id}`,
  petEdit: (id: string) => `/pets/${id}/edit`,
  appointments: '/appointments',
  vaccines: '/vaccines',
  users: '/users',
  userNew: '/users/new',
  userEdit: (id: string) => `/users/${id}/edit`,
  forbidden: '/403',
  notFound: '*',
} as const
